-- 1. Tabela de Contas / Fornecedores / Clientes
create table if not exists public.accounts (
  id bigint generated by default as identity primary key,
  name text not null,
  document text,
  document_type text,
  created_at timestamptz not null default now()
);

-- 2. Tabela de Categorias
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

-- 3. Tabela de Transações / Lançamentos
create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.accounts(id) on delete cascade,
  category_id bigint references public.categories(id) on delete set null,
  due_date date not null,
  supplier text,
  amount numeric(14, 2) not null default 0,
  status text not null default 'Pendente',
  current_installment integer not null default 1,
  total_installment integer not null default 1,
  group_id uuid,
  nfe_url text,
  xml_url text,
  boleto_url text,
  receipt_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint transactions_status_check
    check (status in ('Pago', 'Pendente')),

  constraint transactions_amount_check
    check (amount >= 0),

  constraint transactions_installments_check
    check (
      current_installment >= 1
      and total_installment >= 1
      and current_installment <= total_installment
    )
);

-- 4. Criação dos Índices
create index if not exists transactions_account_id_idx on public.transactions(account_id);
create index if not exists transactions_category_id_idx on public.transactions(category_id);
create index if not exists transactions_due_date_idx on public.transactions(due_date);
create index if not exists transactions_group_id_idx on public.transactions(group_id);
create index if not exists transactions_status_idx on public.transactions(status);