export const mockData = {
  user: {
    name: "Rosangela",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rosangela",
  },

  kpis: [
    {
      id: 1,
      title: "Gastos do Mês",
      value: "R$ 8.750,00",
      icon: "TrendingDown",
      color: "from-primary-400 to-primary-600",
      textColor: "text-primary-600",
    },
    {
      id: 2,
      title: "Contas Pagas",
      value: "15",
      icon: "CheckCircle",
      color: "from-accent-green to-green-400",
      textColor: "text-green-600",
    },
    {
      id: 3,
      title: "Contas Pendentes",
      value: "8",
      icon: "AlertCircle",
      color: "from-orange-300 to-orange-400",
      textColor: "text-orange-600",
    },
  ],

  summaryCards: [
    {
      id: 1,
      title: "A vencer na semana",
      value: "R$ 2.340,00",
      subtitle: "3 contas",
      icon: "Calendar",
    },
    {
      id: 2,
      title: "Gastos com Funcionários",
      value: "R$ 4.200,00",
      subtitle: "12 pessoas",
      icon: "Users",
    },
    {
      id: 3,
      title: "Gastos com Fornecedores",
      value: "R$ 1.920,00",
      subtitle: "8 fornecedores",
      icon: "Package",
    },
    {
      id: 4,
      title: "Gastos Gerais",
      value: "R$ 290,00",
      subtitle: "5 itens",
      icon: "ShoppingCart",
    },
  ],

  transactions: [
    {
      id: 1,
      company: "Agrofértil",
      description: "Fertilizante NPK 20-20-20",
      date: "15/01/2024",
      amount: "R$ 1.250,00",
      status: "Pago",
      category: "Fornecedores",
      dueDate: "10/01/2024",
    },
    {
      id: 2,
      company: "MaqCampo",
      description: "Peças de reposição - Plantadeira",
      date: "18/01/2024",
      amount: "R$ 890,00",
      status: "Pendente",
      category: "Fornecedores",
      dueDate: "25/01/2024",
    },
    {
      id: 3,
      company: "CEAGESP",
      description: "Taxa de registro",
      date: "12/01/2024",
      amount: "R$ 150,00",
      status: "Pago",
      category: "Gastos Gerais",
      dueDate: "10/01/2024",
    },
    {
      id: 4,
      company: "Folha de Pagamento",
      description: "Salários - Janeiro",
      date: "01/01/2024",
      amount: "R$ 4.200,00",
      status: "Pago",
      category: "Funcionários",
      dueDate: "01/01/2024",
    },
    {
      id: 5,
      company: "Sertão Sementes",
      description: "Sementes de milho híbrido",
      date: "20/01/2024",
      amount: "R$ 2.100,00",
      status: "Pendente",
      category: "Fornecedores",
      dueDate: "30/01/2024",
    },
    {
      id: 6,
      company: "AgroTech Solutions",
      description: "Consultoria agrícola",
      date: "16/01/2024",
      amount: "R$ 500,00",
      status: "Pago",
      category: "Serviços",
      dueDate: "15/01/2024",
    },
    {
      id: 7,
      company: "Sicredi",
      description: "Tarifa bancária",
      date: "05/01/2024",
      amount: "R$ 45,00",
      status: "Pago",
      category: "Gastos Gerais",
      dueDate: "05/01/2024",
    },
    {
      id: 8,
      company: "Água & Energia",
      description: "Conta de água",
      date: "19/01/2024",
      amount: "R$ 320,00",
      status: "Pendente",
      category: "Gastos Gerais",
      dueDate: "22/01/2024",
    },
  ],

  categoryChartData: [
    { name: "Fornecedores", value: 4240, color: "#7c3aed" },
    { name: "Funcionários", value: 4200, color: "#a8e6cf" },
    { name: "Gastos Gerais", value: 515, color: "#b8e0f5" },
    { name: "Serviços", value: 500, color: "#ffd9a8" },
  ],

  evolutionChartData: [
    { month: "Jan", expenses: 8750, paid: 7800 },
    { month: "Fev", expenses: 9200, paid: 8900 },
    { month: "Mar", expenses: 8300, paid: 8100 },
    { month: "Abr", expenses: 9800, paid: 9500 },
    { month: "Mai", expenses: 8900, paid: 8700 },
    { month: "Jun", expenses: 10200, paid: 9800 },
  ],
};
